/**
 * TOPIC REGISTRY - FlowLearn
 * ==========================
 *
 * Metadata registry for all technical topics.
 * Actual data is lazy-loaded via dynamic import() when user navigates to a topic.
 */

export const topicsRegistry = [
  {
    id: 'cybersecurity',
    title: 'Cybersecurity',
    titleIt: 'Sicurezza Informatica',
    icon: '\u{1F6E1}\uFE0F',
    description: 'Learn English cybersecurity terminology',
    descriptionIt: 'Impara la terminologia inglese della sicurezza informatica',
    levelCount: 12,
    color: '#ef4444',
  },
  {
    id: 'python',
    title: 'Python Programming',
    titleIt: 'Programmazione Python',
    icon: '\u{1F40D}',
    description: 'Learn English Python programming terminology',
    descriptionIt: 'Impara la terminologia inglese della programmazione Python',
    levelCount: 12,
    color: '#3b82f6',
  },
  {
    id: 'linux',
    title: 'Linux',
    titleIt: 'Linux / Linea di Comando',
    icon: '\u{1F427}',
    description: 'Learn English Linux and command line terminology',
    descriptionIt: 'Impara la terminologia inglese di Linux e della linea di comando',
    levelCount: 12,
    color: '#f59e0b',
  },
  {
    id: 'software-dev',
    title: 'Software Development',
    titleIt: 'Sviluppo Software',
    icon: '\u2699\uFE0F',
    description: 'Learn English software development terminology',
    descriptionIt: 'Impara la terminologia inglese dello sviluppo software',
    levelCount: 12,
    color: '#10b981',
  },
  {
    id: 'ai-engineering',
    title: 'AI Engineering',
    titleIt: 'Ingegneria IA',
    icon: '\u{1F916}',
    description: 'Learn English AI and machine learning terminology',
    descriptionIt: "Impara la terminologia inglese dell'intelligenza artificiale",
    levelCount: 24,
    color: '#8b5cf6',
  },
  {
    id: 'ethical-hacking',
    title: 'Ethical Hacking',
    titleIt: 'Hacking Etico',
    icon: '\u{1F513}',
    description: 'Learn English ethical hacking and penetration testing terminology',
    descriptionIt: "Impara la terminologia inglese dell'hacking etico e del penetration testing",
    levelCount: 24,
    color: '#dc2626',
  },
  {
    id: 'docker-k8s',
    title: 'Docker & Kubernetes',
    titleIt: 'Docker e Kubernetes',
    icon: '\u{1F433}',
    description: 'Learn English container and orchestration terminology',
    descriptionIt: 'Impara la terminologia inglese di container e orchestrazione',
    levelCount: 24,
    color: '#0ea5e9',
  },
  {
    id: 'system-monitoring',
    title: 'System Monitoring',
    titleIt: 'Monitoraggio Sistemi',
    icon: '\u{1F4CA}',
    description: 'Learn English observability and monitoring terminology',
    descriptionIt: "Impara la terminologia inglese dell'osservabilit\u00E0 e del monitoraggio",
    levelCount: 24,
    color: '#f97316',
  },
  {
    id: 'devsecops',
    title: 'DevSecOps',
    titleIt: 'DevSecOps',
    icon: '\u{1F512}',
    description: 'Learn English DevSecOps and security automation terminology',
    descriptionIt: "Impara la terminologia inglese del DevSecOps e dell'automazione della sicurezza",
    levelCount: 24,
    color: '#059669',
  },
  {
    id: 'c-programming',
    title: 'C Programming',
    titleIt: 'Programmazione C',
    icon: '\u2699\uFE0F',
    description: 'Learn English C programming terminology',
    descriptionIt: 'Impara la terminologia inglese della programmazione C',
    levelCount: 24,
    color: '#6366f1',
  },
  {
    id: 'cpp',
    title: 'C++ Programming',
    titleIt: 'Programmazione C++',
    icon: '\u2795',
    description: 'Learn English C++ programming terminology',
    descriptionIt: 'Impara la terminologia inglese della programmazione C++',
    levelCount: 24,
    color: '#4f46e5',
  },
  {
    id: 'nodejs',
    title: 'Node.js',
    titleIt: 'Node.js',
    icon: '\u{1F7E2}',
    description: 'Learn English Node.js and backend JavaScript terminology',
    descriptionIt: 'Impara la terminologia inglese di Node.js e del JavaScript backend',
    levelCount: 24,
    color: '#22c55e',
  },
  {
    id: 'rust',
    title: 'Rust Programming',
    titleIt: 'Programmazione Rust',
    icon: '\u{1F980}',
    description: 'Learn English Rust programming terminology',
    descriptionIt: 'Impara la terminologia inglese della programmazione Rust',
    levelCount: 24,
    color: '#ea580c',
  },
  {
    id: 'cloud-computing',
    title: 'Cloud Computing',
    titleIt: 'Cloud Computing',
    icon: '\u2601\uFE0F',
    description: 'Learn English cloud computing terminology',
    descriptionIt: 'Impara la terminologia inglese del cloud computing',
    levelCount: 24,
    color: '#0284c7',
  },
  {
    id: 'networking',
    title: 'Networking Fundamentals',
    titleIt: 'Fondamenti di Rete',
    icon: '\u{1F310}',
    description: 'Learn English networking and protocol terminology',
    descriptionIt: 'Impara la terminologia inglese delle reti e dei protocolli',
    levelCount: 24,
    color: '#7c3aed',
  },
  {
    id: 'databases',
    title: 'Databases (SQL & NoSQL)',
    titleIt: 'Database (SQL e NoSQL)',
    icon: '\u{1F5C4}\uFE0F',
    description: 'Learn English database terminology',
    descriptionIt: 'Impara la terminologia inglese dei database',
    levelCount: 24,
    color: '#0891b2',
  },
  {
    id: 'git-vcs',
    title: 'Git & Version Control',
    titleIt: 'Git e Controllo Versione',
    icon: '\u{1F500}',
    description: 'Learn English Git and version control terminology',
    descriptionIt: 'Impara la terminologia inglese di Git e del controllo versione',
    levelCount: 24,
    color: '#a855f7',
  },
];

/**
 * Get a topic by ID
 */
export function getTopicMeta(topicId) {
  return topicsRegistry.find((t) => t.id === topicId) || null;
}
